version: "3.1"

services: 
  codes:
    restart: always
    # build: ./codes # Uncomment this line if you want to built it from the source code
    image: aohorodnyk/ws-return-codes
    container_name: codes
    networks:
      - codes
  nginx:
    restart: always
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./conf:/etc/nginx/conf.d
    networks:
      - codes

networks:
    codes:
